# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieverMobile', models.CharField(max_length=11, verbose_name='收货人手机')),
                ('province', models.CharField(max_length=20, verbose_name='地址（省）')),
                ('city', models.CharField(max_length=20, verbose_name='地址（市）')),
                ('region', models.CharField(max_length=20, verbose_name='地址（区）')),
                ('detail', models.TextField(verbose_name='详细地址')),
                ('recieverName', models.CharField(max_length=30, verbose_name='收货人姓名')),
                ('isDefault', models.BooleanField(default=False, verbose_name='默认地址')),
            ],
            options={
                'db_table': 'Address',
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=200, verbose_name='图书名称')),
                ('bookPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='图书价格')),
                ('bookPhoto', models.ImageField(blank=True, null=True, upload_to='static/img/upload/book', verbose_name='图书封面')),
                ('bookIntr', models.TextField(blank=True, null=True, verbose_name='图书描述')),
                ('bookStock', models.IntegerField(verbose_name='图书库存')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='折扣')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(max_length=40, verbose_name='出版社')),
                ('publishTime', models.DateField(verbose_name='出版日期')),
                ('isOnsale', models.BooleanField(verbose_name='是否在售')),
            ],
            options={
                'db_table': 'book',
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookAmount', models.IntegerField(blank=True, null=True, verbose_name='购买图书数量')),
                ('bookRefund', models.IntegerField(blank=True, null=True, verbose_name='退货图书数量')),
                ('bookPrice', models.FloatField(null=True, verbose_name='图书单价')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Book', verbose_name='图书')),
            ],
            options={
                'db_table': 'booklist',
                'verbose_name': '订单图书',
                'verbose_name_plural': '订单图书',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20, verbose_name='类型名称')),
                ('typePhoto', models.ImageField(blank=True, null=True, upload_to='static/img/upload/booktype', verbose_name='类型图片')),
                ('typeIntr', models.TextField(blank=True, null=True, verbose_name='类型描述')),
            ],
            options={
                'db_table': 'booktype',
                'verbose_name': '图书类型',
                'verbose_name_plural': '图书类型',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='购买数量')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Book', verbose_name='书籍')),
            ],
            options={
                'db_table': 'cart',
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('emoji', models.ImageField(blank=True, null=True, upload_to='', verbose_name='表情')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='时间')),
                ('identity', models.CharField(choices=[('user', '用户'), ('cc', '客服')], max_length=10, verbose_name='发送消息人的身份')),
            ],
            options={
                'db_table': 'chat',
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
            },
        ),
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccName', models.CharField(max_length=20, verbose_name='客服名称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('ccImage', models.ImageField(blank=True, null=True, upload_to='static/img/upload/customercare', verbose_name='客服头像')),
                ('isLogin', models.BooleanField(default=False, verbose_name='是否登录')),
                ('isChat', models.BooleanField(default=False, verbose_name='是否在聊天')),
            ],
            options={
                'db_table': 'customercare',
                'verbose_name': '客服',
                'verbose_name_plural': '客服',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='static/img/upload/refund', verbose_name='图片凭证')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinionTime', models.DateField(null=True, verbose_name='评论时间')),
                ('level', models.CharField(choices=[('好评', '好评'), ('中评', '中评'), ('差评', '差评')], max_length=20, verbose_name='评价等级')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/upload/opinion', verbose_name='评价图片')),
                ('detail', models.TextField(verbose_name='评价详情')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Book', verbose_name='图书')),
            ],
            options={
                'db_table': 'opinion',
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTime', models.DateField(verbose_name='下单时间')),
                ('orderState', models.CharField(choices=[('待付款', '待付款'), ('待发货', '待发货'), ('待收货', '待收货'), ('待评价', '待评价'), ('已收货', '已收货'), ('已取消', '已取消'), ('已完成', '已完成')], max_length=20, verbose_name='订单状态')),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='订单金额')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Address', verbose_name='配送地址')),
            ],
            options={
                'db_table': 'purchase',
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejectTime', models.DateField(auto_now_add=True, verbose_name='申请时间')),
                ('rejectAmount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='退款金额')),
                ('rejectReason', models.TextField(verbose_name='退款原因')),
                ('rejectState', models.CharField(choices=[('退货中', '退货中'), ('已退货', '已退货')], max_length=20, verbose_name='退款状态')),
                ('img', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Img', verbose_name='图片凭证')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Purchase', verbose_name='订单')),
            ],
            options={
                'db_table': 'reject',
                'verbose_name': '退货单',
                'verbose_name_plural': '退货单',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, verbose_name='用户名')),
                ('userPassword', models.CharField(max_length=200, verbose_name='用户密码')),
                ('userMobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='用户手机')),
                ('userEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='用户邮箱')),
                ('userImage', models.ImageField(blank=True, null=True, upload_to='static/img/upload/user', verbose_name='用户头像')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='余额')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Purchase', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='customercare',
            name='chatUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='聊天用户'),
        ),
        migrations.AddField(
            model_name='chat',
            name='ccSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.CustomerCare', verbose_name='客服'),
        ),
        migrations.AddField(
            model_name='chat',
            name='userSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Purchase', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='reject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Reject', verbose_name='退货单'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookType',
            field=models.ManyToManyField(to='index.BookType', verbose_name='图书类型'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='用户'),
        ),
    ]
