# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='image',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='opinionTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='评论时间'),
        ),
    ]
